### PR TITLE
Pull 2 Develop

### PR DESCRIPTION
**Pull request by divesh987**
New heading

### CODE REVIEW

**Review by richgurney — DISMISSED** [review]
Can you sort out your indentation

**Comment by richgurney** [comment]
HI Divesh, your changes have come up for me to review. Im expecting that your not ready to merge this into master? I have had a look and there are a few things you need to address.

1) Go through your code and tidy the console.logs before we go live
2) Have a general tidy up and make things looks nice
3) You need to address the $ in variables where you have not used jQuery
4) Looking at the game, can we have some clear identifiers of when the game has started and finished with a clear display of score at the end. 
5) You also seems to have some listeners that are not been turned off so there are points when you 
 can click the circles even outside of game

**Comment by divesh987** [comment]
Hi Richard, no this is not the one ready for merging .it was the heading one u wanted to test out yesterday. Because of my pushes it has come to the latest version. Thank you for the feedback. It's now getting clear on the changes I need to make.

**Review by richgurney — CHANGES_REQUESTED** [review]
Can you fix the indentation in the main.js and index.html

**Review by richgurney — APPROVED** [review]
Thanks, indentation looks much better, missed one on line 88 of main.js but I will send it through

**Pull request merged**
